unit ami_event_map;

{$mode objfpc}{$H+}

interface

uses
  SysUtils, Generics.Collections, ami_enums;

type
  TEventTypeMap = specialize TDictionary<String, TAMIEventType>;
  TEventPriorityMap = specialize TDictionary<TAMIEventType, Integer>;
  TEventCategoryMap = specialize TDictionary<TAMIEventType, String>;

function EventTypeMap: TEventTypeMap;
function EventPriorityMap: TEventPriorityMap;
function EventCategoryMap: TEventCategoryMap;

implementation

var
  FEventTypeMap: TEventTypeMap;
  FEventPriorityMap: TEventPriorityMap;
  FEventCategoryMap: TEventCategoryMap;

function EventTypeMap: TEventTypeMap;
begin
  Result := FEventTypeMap;
end;

function EventPriorityMap: TEventPriorityMap;
begin
  Result := FEventPriorityMap;
end;

function EventCategoryMap: TEventCategoryMap;
begin
  Result := FEventCategoryMap;
end;

procedure InitializeMaps;
begin
  FEventTypeMap := TEventTypeMap.Create;
  FEventPriorityMap := TEventPriorityMap.Create;
  FEventCategoryMap := TEventCategoryMap.Create;

  // Event type mappings
  FEventTypeMap.Add('UNKNOWN', etUnknown);
  FEventTypeMap.Add('AGIEXECEND', etAGIExecEnd);
  FEventTypeMap.Add('AGIEXECSTART', etAGIExecStart);
  FEventTypeMap.Add('ASYNCAGIEND', etAsyncAGIEnd);
  FEventTypeMap.Add('ASYNCAGIEXEC', etAsyncAGIExec);
  FEventTypeMap.Add('ASYNCAGISTART', etAsyncAGIStart);
  FEventTypeMap.Add('AOC_D', etAOC_D);
  FEventTypeMap.Add('AOC_E', etAOC_E);
  FEventTypeMap.Add('AOC_S', etAOC_S);
  FEventTypeMap.Add('AGENTCALLED', etAgentCalled);
  FEventTypeMap.Add('AGENTCOMPLETE', etAgentComplete);
  FEventTypeMap.Add('AGENTCONNECT', etAgentConnect);
  FEventTypeMap.Add('AGENTDUMP', etAgentDump);
  FEventTypeMap.Add('AGENTLOGIN', etAgentLogin);
  FEventTypeMap.Add('AGENTLOGOFF', etAgentLogoff);
  FEventTypeMap.Add('AGENTRINGNOANSWER', etAgentRingNoAnswer);
  FEventTypeMap.Add('AGENTS', etAgents);
  FEventTypeMap.Add('AGENTSCOMPLETE', etAgentsComplete);
  FEventTypeMap.Add('ALARM', etAlarm);
  FEventTypeMap.Add('ALARMCLEAR', etAlarmClear);
  FEventTypeMap.Add('SPANALARM', etSpanAlarm);
  FEventTypeMap.Add('SPANALARMCLEAR', etSpanAlarmClear);
  FEventTypeMap.Add('AORDETAIL', etAorDetail);
  FEventTypeMap.Add('AORLIST', etAorList);
  FEventTypeMap.Add('AORLISTCOMPLETE', etAorListComplete);
  FEventTypeMap.Add('AUTHDETAIL', etAuthDetail);
  FEventTypeMap.Add('AUTHLIST', etAuthList);
  FEventTypeMap.Add('AUTHLISTCOMPLETE', etAuthListComplete);
  FEventTypeMap.Add('AUTHMETHODNOTALLOWED', etAuthMethodNotAllowed);
  FEventTypeMap.Add('CHALLENGERESPONSEFAILED', etChallengeResponseFailed);
  FEventTypeMap.Add('CHALLENGESENT', etChallengeSent);
  FEventTypeMap.Add('FAILEDACL', etFailedACL);
  FEventTypeMap.Add('INVALIDACCOUNTID', etInvalidAccountID);
  FEventTypeMap.Add('INVALIDPASSWORD', etInvalidPassword);
  FEventTypeMap.Add('INVALIDTRANSPORT', etInvalidTransport);
  FEventTypeMap.Add('REQUESTBADFORMAT', etRequestBadFormat);
  FEventTypeMap.Add('REQUESTNOTALLOWED', etRequestNotAllowed);
  FEventTypeMap.Add('REQUESTNOTSUPPORTED', etRequestNotSupported);
  FEventTypeMap.Add('SUCCESSFULAUTH', etSuccessfulAuth);
  FEventTypeMap.Add('UNEXPECTEDADDRESS', etUnexpectedAddress);
  FEventTypeMap.Add('BRIDGECREATE', etBridgeCreate);
  FEventTypeMap.Add('BRIDGEDESTROY', etBridgeDestroy);
  FEventTypeMap.Add('BRIDGEENTER', etBridgeEnter);
  FEventTypeMap.Add('BRIDGEINFOCHANNEL', etBridgeInfoChannel);
  FEventTypeMap.Add('BRIDGEINFOCOMPLETE', etBridgeInfoComplete);
  FEventTypeMap.Add('BRIDGELEAVE', etBridgeLeave);
  FEventTypeMap.Add('BRIDGEMERGE', etBridgeMerge);
  FEventTypeMap.Add('BRIDGEVIDEOSOURCEUPDATE', etBridgeVideoSourceUpdate);
  FEventTypeMap.Add('LOCALBRIDGE', etLocalBridge);
  FEventTypeMap.Add('LOCALOPTIMIZATIONBEGIN', etLocalOptimizationBegin);
  FEventTypeMap.Add('LOCALOPTIMIZATIONEND', etLocalOptimizationEnd);
  FEventTypeMap.Add('CEL', etCEL);
  FEventTypeMap.Add('CDR', etCdr);
  FEventTypeMap.Add('CHANNELTALKINGSTART', etChannelTalkingStart);
  FEventTypeMap.Add('CHANNELTALKINGSTOP', etChannelTalkingStop);
  FEventTypeMap.Add('CORESHOWCHANNEL', etCoreShowChannel);
  FEventTypeMap.Add('CORESHOWCHANNELSCOMPLETE', etCoreShowChannelsComplete);
  FEventTypeMap.Add('DAHDICHANNEL', etDAHDIChannel);
  FEventTypeMap.Add('DEVICESTATECHANGE', etDeviceStateChange);
  FEventTypeMap.Add('DEVICESTATELISTCOMPLETE', etDeviceStateListComplete);
  FEventTypeMap.Add('DNDSTATE', etDNDState);
  FEventTypeMap.Add('EXTENSIONSTATELISTCOMPLETE', etExtensionStateListComplete);
  FEventTypeMap.Add('EXTENSIONSTATUS', etExtensionStatus);
  FEventTypeMap.Add('HANGUP', etHangup);
  FEventTypeMap.Add('HANGUPHANDLERPOP', etHangupHandlerPop);
  FEventTypeMap.Add('HANGUPHANDLERPUSH', etHangupHandlerPush);
  FEventTypeMap.Add('HANGUPHANDLERRUN', etHangupHandlerRun);
  FEventTypeMap.Add('HANGUPREQUEST', etHangupRequest);
  FEventTypeMap.Add('HOLD', etHold);
  FEventTypeMap.Add('LOGCHANNEL', etLogChannel);
  FEventTypeMap.Add('MONITORSTART', etMonitorStart);
  FEventTypeMap.Add('MONITORSTOP', etMonitorStop);
  FEventTypeMap.Add('MUSICONHOLDSTART', etMusicOnHoldStart);
  FEventTypeMap.Add('MUSICONHOLDSTOP', etMusicOnHoldStop);
  FEventTypeMap.Add('NEWACCOUNTCODE', etNewAccountCode);
  FEventTypeMap.Add('NEWCALLERID', etNewCallerid);
  FEventTypeMap.Add('NEWCONNECTEDLINE', etNewConnectedLine);
  FEventTypeMap.Add('NEWEXTEN', etNewExten);
  FEventTypeMap.Add('NEWCHANNEL', etNewchannel);
  FEventTypeMap.Add('NEWSTATE', etNewstate);
  FEventTypeMap.Add('ORIGINATERESPONSE', etOriginateResponse);
  FEventTypeMap.Add('PICKUP', etPickup);
  FEventTypeMap.Add('RENAME', etRename);
  FEventTypeMap.Add('SOFTHANGUPREQUEST', etSoftHangupRequest);
  FEventTypeMap.Add('STATUS', etStatus);
  FEventTypeMap.Add('STATUSCOMPLETE', etStatusComplete);
  FEventTypeMap.Add('UNHOLD', etUnhold);
  FEventTypeMap.Add('CONFBRIDGEEND', etConfbridgeEnd);
  FEventTypeMap.Add('CONFBRIDGEJOIN', etConfbridgeJoin);
  FEventTypeMap.Add('CONFBRIDGELEAVE', etConfbridgeLeave);
  FEventTypeMap.Add('CONFBRIDGELIST', etConfbridgeList);
  FEventTypeMap.Add('CONFBRIDGELISTCOMPLETE', etConfbridgeListComplete);
  FEventTypeMap.Add('CONFBRIDGELISTROOMS', etConfbridgeListRooms);
  FEventTypeMap.Add('CONFBRIDGEMUTE', etConfbridgeMute);
  FEventTypeMap.Add('CONFBRIDGERECORD', etConfbridgeRecord);
  FEventTypeMap.Add('CONFBRIDGESTART', etConfbridgeStart);
  FEventTypeMap.Add('CONFBRIDGESTOPRECORD', etConfbridgeStopRecord);
  FEventTypeMap.Add('CONFBRIDGETALKING', etConfbridgeTalking);
  FEventTypeMap.Add('CONFBRIDGEUNMUTE', etConfbridgeUnmute);
  FEventTypeMap.Add('CONTACTLIST', etContactList);
  FEventTypeMap.Add('CONTACTLISTCOMPLETE', etContactListComplete);
  FEventTypeMap.Add('CONTACTSTATUS', etContactStatus);
  FEventTypeMap.Add('CONTACTSTATUSDETAIL', etContactStatusDetail);
  FEventTypeMap.Add('DIALBEGIN', etDialBegin);
  FEventTypeMap.Add('DIALEND', etDialEnd);
  FEventTypeMap.Add('DIALSTATE', etDialState);
  FEventTypeMap.Add('DTMFBEGIN', etDTMFBegin);
  FEventTypeMap.Add('DTMFEND', etDTMFEnd);
  FEventTypeMap.Add('ENDPOINTDETAIL', etEndpointDetail);
  FEventTypeMap.Add('ENDPOINTDETAILCOMPLETE', etEndpointDetailComplete);
  FEventTypeMap.Add('ENDPOINTLIST', etEndpointList);
  FEventTypeMap.Add('ENDPOINTLISTCOMPLETE', etEndpointListComplete);
  FEventTypeMap.Add('IDENTIFYDETAIL', etIdentifyDetail);
  FEventTypeMap.Add('TRANSPORTDETAIL', etTransportDetail);
  FEventTypeMap.Add('FAXSESSION', etFAXSession);
  FEventTypeMap.Add('FAXSESSIONSCOMPLETE', etFAXSessionsComplete);
  FEventTypeMap.Add('FAXSESSIONSENTRY', etFAXSessionsEntry);
  FEventTypeMap.Add('FAXSTATS', etFAXStats);
  FEventTypeMap.Add('FAXSTATUS', etFAXStatus);
  FEventTypeMap.Add('RECEIVEFAX', etReceiveFAX);
  FEventTypeMap.Add('SENDFAX', etSendFAX);
  FEventTypeMap.Add('DEADLOCKSTART', etDeadlockStart);
  FEventTypeMap.Add('FLASH', etFlash);
  FEventTypeMap.Add('FULLYBOOTED', etFullyBooted);
  FEventTypeMap.Add('LOAD', etLoad);
  FEventTypeMap.Add('LOADAVERAGELIMIT', etLoadAverageLimit);
  FEventTypeMap.Add('MEMORYLIMIT', etMemoryLimit);
  FEventTypeMap.Add('RELOAD', etReload);
  FEventTypeMap.Add('SESSIONLIMIT', etSessionLimit);
  FEventTypeMap.Add('SESSIONTIMEOUT', etSessionTimeout);
  FEventTypeMap.Add('SHUTDOWN', etShutdown);
  FEventTypeMap.Add('UNLOAD', etUnload);
  FEventTypeMap.Add('WINK', etWink);
  FEventTypeMap.Add('MEETMEEND', etMeetmeEnd);
  FEventTypeMap.Add('MEETMEJOIN', etMeetmeJoin);
  FEventTypeMap.Add('MEETMELEAVE', etMeetmeLeave);
  FEventTypeMap.Add('MEETMELIST', etMeetmeList);
  FEventTypeMap.Add('MEETMELISTROOMS', etMeetmeListRooms);
  FEventTypeMap.Add('MEETMEMUTE', etMeetmeMute);
  FEventTypeMap.Add('MEETMETALKREQUEST', etMeetmeTalkRequest);
  FEventTypeMap.Add('MEETMETALKING', etMeetmeTalking);
  FEventTypeMap.Add('MESSAGEWAITING', etMessageWaiting);
  FEventTypeMap.Add('MINIVOICEMAIL', etMiniVoiceMail);
  FEventTypeMap.Add('MWIGET', etMWIGet);
  FEventTypeMap.Add('MWIGETCOMPLETE', etMWIGetComplete);
  FEventTypeMap.Add('MIXMONITORMUTE', etMixMonitorMute);
  FEventTypeMap.Add('MIXMONITORSTART', etMixMonitorStart);
  FEventTypeMap.Add('MIXMONITORSTOP', etMixMonitorStop);
  FEventTypeMap.Add('PARKEDCALL', etParkedCall);
  FEventTypeMap.Add('PARKEDCALLGIVEUP', etParkedCallGiveUp);
  FEventTypeMap.Add('PARKEDCALLSWAP', etParkedCallSwap);
  FEventTypeMap.Add('PARKEDCALLTIMEOUT', etParkedCallTimeOut);
  FEventTypeMap.Add('UNPARKEDCALL', etUnParkedCall);
  FEventTypeMap.Add('PEERSTATUS', etPeerStatus);
  FEventTypeMap.Add('REGISTRY', etRegistry);
  FEventTypeMap.Add('SIPQUALIFYPEERDONE', etSIPQualifyPeerDone);
  FEventTypeMap.Add('PRESENCESTATECHANGE', etPresenceStateChange);
  FEventTypeMap.Add('PRESENCESTATELISTCOMPLETE', etPresenceStateListComplete);
  FEventTypeMap.Add('PRESENCESTATUS', etPresenceStatus);
  FEventTypeMap.Add('QUEUECALLERABANDON', etQueueCallerAbandon);
  FEventTypeMap.Add('QUEUECALLERJOIN', etQueueCallerJoin);
  FEventTypeMap.Add('QUEUECALLERLEAVE', etQueueCallerLeave);
  FEventTypeMap.Add('QUEUEENTRY', etQueueEntry);
  FEventTypeMap.Add('QUEUEMEMBER', etQueueMember);
  FEventTypeMap.Add('QUEUEMEMBERADDED', etQueueMemberAdded);
  FEventTypeMap.Add('QUEUEMEMBERPAUSE', etQueueMemberPause);
  FEventTypeMap.Add('QUEUEMEMBERPENALTY', etQueueMemberPenalty);
  FEventTypeMap.Add('QUEUEMEMBERREMOVED', etQueueMemberRemoved);
  FEventTypeMap.Add('QUEUEMEMBERRINGINUSE', etQueueMemberRinginuse);
  FEventTypeMap.Add('QUEUEMEMBERSTATUS', etQueueMemberStatus);
  FEventTypeMap.Add('QUEUEPARAMS', etQueueParams);
  FEventTypeMap.Add('QUEUESTATUSCOMPLETE', etQueueStatusComplete);
  FEventTypeMap.Add('QUEUESUMMARYCOMPLETE', etQueueSummaryComplete);
  FEventTypeMap.Add('RTCPRECEIVED', etRTCPReceived);
  FEventTypeMap.Add('RTCPSENT', etRTCPSent);
  FEventTypeMap.Add('CHANSPYSTART', etChanSpyStart);
  FEventTypeMap.Add('CHANSPYSTOP', etChanSpyStop);
  FEventTypeMap.Add('ATTENDEDTRANSFER', etAttendedTransfer);
  FEventTypeMap.Add('BLINDTRANSFER', etBlindTransfer);
  FEventTypeMap.Add('USEREVENT', etUserEvent);
  FEventTypeMap.Add('VARSET', etVarSet);
  FEventTypeMap.Add('MCID', etMCID);
  FEventTypeMap.Add('DBGETRESPONSE', etDBGetResponse);
  FEventTypeMap.Add('DBGETCOMPLETE', etDBGetComplete);
  FEventTypeMap.Add('CHANNELHUNGUP', etChannelHungup);
  FEventTypeMap.Add('CHANNELSHUNGUPLISTCOMPLETE', etChannelsHungupListComplete);

  // Event priority mappings
  FEventPriorityMap.Add(etHangup, 100);
  FEventPriorityMap.Add(etHangupRequest, 100);
  FEventPriorityMap.Add(etNewchannel, 100);
  FEventPriorityMap.Add(etSoftHangupRequest, 100);
  FEventPriorityMap.Add(etChannelHungup, 100);
  FEventPriorityMap.Add(etDialBegin, 90);
  FEventPriorityMap.Add(etDialEnd, 90);
  FEventPriorityMap.Add(etDialState, 90);
  FEventPriorityMap.Add(etAgentCalled, 90);
  FEventPriorityMap.Add(etAgentConnect, 90);
  FEventPriorityMap.Add(etBridgeCreate, 85);
  FEventPriorityMap.Add(etBridgeDestroy, 85);
  FEventPriorityMap.Add(etBridgeEnter, 85);
  FEventPriorityMap.Add(etBridgeLeave, 85);
  FEventPriorityMap.Add(etHold, 85);
  FEventPriorityMap.Add(etUnhold, 85);
  FEventPriorityMap.Add(etMusicOnHoldStart, 85);
  FEventPriorityMap.Add(etMusicOnHoldStop, 85);
  FEventPriorityMap.Add(etAttendedTransfer, 85);
  FEventPriorityMap.Add(etBlindTransfer, 85);
  FEventPriorityMap.Add(etAgentComplete, 80);
  FEventPriorityMap.Add(etAgentRingNoAnswer, 80);
  FEventPriorityMap.Add(etAgentDump, 80);
  FEventPriorityMap.Add(etDeadlockStart, 80);
  FEventPriorityMap.Add(etFullyBooted, 80);
  FEventPriorityMap.Add(etShutdown, 80);
  FEventPriorityMap.Add(etNewstate, 75);
  FEventPriorityMap.Add(etAuthMethodNotAllowed, 75);
  FEventPriorityMap.Add(etSuccessfulAuth, 75);
  FEventPriorityMap.Add(etFailedACL, 75);
  FEventPriorityMap.Add(etNewCallerid, 70);
  FEventPriorityMap.Add(etNewConnectedLine, 70);
  FEventPriorityMap.Add(etQueueCallerAbandon, 60);
  FEventPriorityMap.Add(etQueueCallerJoin, 60);
  FEventPriorityMap.Add(etQueueCallerLeave, 60);
  FEventPriorityMap.Add(etQueueEntry, 60);
  FEventPriorityMap.Add(etQueueMember, 55);
  FEventPriorityMap.Add(etQueueMemberAdded, 55);
  FEventPriorityMap.Add(etQueueMemberPause, 55);
  FEventPriorityMap.Add(etQueueMemberRemoved, 55);
  FEventPriorityMap.Add(etQueueMemberRinginuse, 55);
  FEventPriorityMap.Add(etQueueMemberStatus, 55);
  FEventPriorityMap.Add(etQueueParams, 55);
  FEventPriorityMap.Add(etQueueStatusComplete, 55);
  FEventPriorityMap.Add(etParkedCall, 55);
  FEventPriorityMap.Add(etUnParkedCall, 55);
  FEventPriorityMap.Add(etDeviceStateChange, 50);
  FEventPriorityMap.Add(etAgentLogin, 50);
  FEventPriorityMap.Add(etAgentLogoff, 50);
  FEventPriorityMap.Add(etPeerStatus, 50);
  FEventPriorityMap.Add(etRegistry, 50);
  FEventPriorityMap.Add(etSIPQualifyPeerDone, 50);
  FEventPriorityMap.Add(etCdr, 40);
  FEventPriorityMap.Add(etCEL, 40);
  FEventPriorityMap.Add(etMessageWaiting, 40);
  FEventPriorityMap.Add(etMiniVoiceMail, 40);
  FEventPriorityMap.Add(etMWIGet, 40);
  FEventPriorityMap.Add(etMWIGetComplete, 40);
  FEventPriorityMap.Add(etDTMFBegin, 35);
  FEventPriorityMap.Add(etDTMFEnd, 35);
  FEventPriorityMap.Add(etLoad, 30);
  FEventPriorityMap.Add(etReload, 30);
  FEventPriorityMap.Add(etUnknown, 25);
  FEventPriorityMap.Add(etUserEvent, 25);
  FEventPriorityMap.Add(etVarSet, 25);
  FEventPriorityMap.Add(etAGIExecEnd, 25);
  FEventPriorityMap.Add(etAGIExecStart, 25);
  FEventPriorityMap.Add(etAsyncAGIEnd, 25);
  FEventPriorityMap.Add(etAsyncAGIExec, 25);
  FEventPriorityMap.Add(etAsyncAGIStart, 25);
  FEventPriorityMap.Add(etAgents, 25);
  FEventPriorityMap.Add(etAgentsComplete, 25);
  FEventPriorityMap.Add(etAorListComplete, 25);
  FEventPriorityMap.Add(etAuthListComplete, 25);
  FEventPriorityMap.Add(etBridgeInfoComplete, 25);
  FEventPriorityMap.Add(etCoreShowChannel, 25);
  FEventPriorityMap.Add(etCoreShowChannelsComplete, 25);
  FEventPriorityMap.Add(etDeviceStateListComplete, 25);
  FEventPriorityMap.Add(etExtensionStatus, 25);
  FEventPriorityMap.Add(etExtensionStateListComplete, 25);
  FEventPriorityMap.Add(etOriginateResponse, 25);
  FEventPriorityMap.Add(etStatusComplete, 25);
  FEventPriorityMap.Add(etConfbridgeListComplete, 25);
  FEventPriorityMap.Add(etEndpointListComplete, 25);
  FEventPriorityMap.Add(etQueueSummaryComplete, 25);
  FEventPriorityMap.Add(etDBGetResponse, 25);
  FEventPriorityMap.Add(etDBGetComplete, 25);
  FEventPriorityMap.Add(etChannelsHungupListComplete, 25);

  // Event category mappings
  FEventCategoryMap.Add(etUnknown, 'Unknown');
  FEventCategoryMap.Add(etAGIExecEnd, 'AGI');
  FEventCategoryMap.Add(etAGIExecStart, 'AGI');
  FEventCategoryMap.Add(etAsyncAGIEnd, 'AGI');
  FEventCategoryMap.Add(etAsyncAGIExec, 'AGI');
  FEventCategoryMap.Add(etAsyncAGIStart, 'AGI');
  FEventCategoryMap.Add(etAOC_D, 'AOC');
  FEventCategoryMap.Add(etAOC_E, 'AOC');
  FEventCategoryMap.Add(etAOC_S, 'AOC');
  FEventCategoryMap.Add(etAgentCalled, 'Agent');
  FEventCategoryMap.Add(etAgentComplete, 'Agent');
  FEventCategoryMap.Add(etAgentConnect, 'Agent');
  FEventCategoryMap.Add(etAgentDump, 'Agent');
  FEventCategoryMap.Add(etAgentLogin, 'Agent');
  FEventCategoryMap.Add(etAgentLogoff, 'Agent');
  FEventCategoryMap.Add(etAgentRingNoAnswer, 'Agent');
  FEventCategoryMap.Add(etAgents, 'Agent');
  FEventCategoryMap.Add(etAgentsComplete, 'Agent');
  FEventCategoryMap.Add(etAlarm, 'Alarm');
  FEventCategoryMap.Add(etAlarmClear, 'Alarm');
  FEventCategoryMap.Add(etSpanAlarm, 'Alarm');
  FEventCategoryMap.Add(etSpanAlarmClear, 'Alarm');
  FEventCategoryMap.Add(etAorDetail, 'PJSIP');
  FEventCategoryMap.Add(etAorList, 'PJSIP');
  FEventCategoryMap.Add(etAorListComplete, 'PJSIP');
  FEventCategoryMap.Add(etAuthDetail, 'Security');
  FEventCategoryMap.Add(etAuthList, 'Security');
  FEventCategoryMap.Add(etAuthListComplete, 'Security');
  FEventCategoryMap.Add(etAuthMethodNotAllowed, 'Security');
  FEventCategoryMap.Add(etChallengeResponseFailed, 'Security');
  FEventCategoryMap.Add(etChallengeSent, 'Security');
  FEventCategoryMap.Add(etFailedACL, 'Security');
  FEventCategoryMap.Add(etInvalidAccountID, 'Security');
  FEventCategoryMap.Add(etInvalidPassword, 'Security');
  FEventCategoryMap.Add(etInvalidTransport, 'Security');
  FEventCategoryMap.Add(etRequestBadFormat, 'Security');
  FEventCategoryMap.Add(etRequestNotAllowed, 'Security');
  FEventCategoryMap.Add(etRequestNotSupported, 'Security');
  FEventCategoryMap.Add(etSuccessfulAuth, 'Security');
  FEventCategoryMap.Add(etUnexpectedAddress, 'Security');
  FEventCategoryMap.Add(etBridgeCreate, 'Bridge');
  FEventCategoryMap.Add(etBridgeDestroy, 'Bridge');
  FEventCategoryMap.Add(etBridgeEnter, 'Bridge');
  FEventCategoryMap.Add(etBridgeInfoChannel, 'Bridge');
  FEventCategoryMap.Add(etBridgeInfoComplete, 'Bridge');
  FEventCategoryMap.Add(etBridgeLeave, 'Bridge');
  FEventCategoryMap.Add(etBridgeMerge, 'Bridge');
  FEventCategoryMap.Add(etBridgeVideoSourceUpdate, 'Bridge');
  FEventCategoryMap.Add(etLocalBridge, 'Bridge');
  FEventCategoryMap.Add(etLocalOptimizationBegin, 'Bridge');
  FEventCategoryMap.Add(etLocalOptimizationEnd, 'Bridge');
  FEventCategoryMap.Add(etCEL, 'CDR');
  FEventCategoryMap.Add(etCdr, 'CDR');
  FEventCategoryMap.Add(etChannelTalkingStart, 'Monitoring');
  FEventCategoryMap.Add(etChannelTalkingStop, 'Monitoring');
  FEventCategoryMap.Add(etCoreShowChannel, 'System');
  FEventCategoryMap.Add(etCoreShowChannelsComplete, 'System');
  FEventCategoryMap.Add(etDAHDIChannel, 'Unknown');
  FEventCategoryMap.Add(etDeviceStateChange, 'DeviceStatus');
  FEventCategoryMap.Add(etDeviceStateListComplete, 'DeviceStatus');
  FEventCategoryMap.Add(etDNDState, 'DeviceStatus');
  FEventCategoryMap.Add(etExtensionStateListComplete, 'DeviceStatus');
  FEventCategoryMap.Add(etExtensionStatus, 'DeviceStatus');
  FEventCategoryMap.Add(etHangup, 'CallControl');
  FEventCategoryMap.Add(etHangupHandlerPop, 'CallControl');
  FEventCategoryMap.Add(etHangupHandlerPush, 'CallControl');
  FEventCategoryMap.Add(etHangupHandlerRun, 'CallControl');
  FEventCategoryMap.Add(etHangupRequest, 'CallControl');
  FEventCategoryMap.Add(etHold, 'CallControl');
  FEventCategoryMap.Add(etLogChannel, 'System');
  FEventCategoryMap.Add(etMonitorStart, 'Monitoring');
  FEventCategoryMap.Add(etMonitorStop, 'Monitoring');
  FEventCategoryMap.Add(etMusicOnHoldStart, 'MusicOnHold');
  FEventCategoryMap.Add(etMusicOnHoldStop, 'MusicOnHold');
  FEventCategoryMap.Add(etNewAccountCode, 'CallControl');
  FEventCategoryMap.Add(etNewCallerid, 'CallControl');
  FEventCategoryMap.Add(etNewConnectedLine, 'CallControl');
  FEventCategoryMap.Add(etNewExten, 'CallControl');
  FEventCategoryMap.Add(etNewchannel, 'CallControl');
  FEventCategoryMap.Add(etNewstate, 'CallControl');
  FEventCategoryMap.Add(etOriginateResponse, 'CallControl');
  FEventCategoryMap.Add(etPickup, 'CallControl');
  FEventCategoryMap.Add(etRename, 'CallControl');
  FEventCategoryMap.Add(etSoftHangupRequest, 'CallControl');
  FEventCategoryMap.Add(etStatus, 'System');
  FEventCategoryMap.Add(etStatusComplete, 'System');
  FEventCategoryMap.Add(etUnhold, 'CallControl');
  FEventCategoryMap.Add(etConfbridgeEnd, 'Conference');
  FEventCategoryMap.Add(etConfbridgeJoin, 'Conference');
  FEventCategoryMap.Add(etConfbridgeLeave, 'Conference');
  FEventCategoryMap.Add(etConfbridgeList, 'Conference');
  FEventCategoryMap.Add(etConfbridgeListComplete, 'Conference');
  FEventCategoryMap.Add(etConfbridgeListRooms, 'Conference');
  FEventCategoryMap.Add(etConfbridgeMute, 'Conference');
  FEventCategoryMap.Add(etConfbridgeRecord, 'Conference');
  FEventCategoryMap.Add(etConfbridgeStart, 'Conference');
  FEventCategoryMap.Add(etConfbridgeStopRecord, 'Conference');
  FEventCategoryMap.Add(etConfbridgeTalking, 'Conference');
  FEventCategoryMap.Add(etConfbridgeUnmute, 'Conference');
  FEventCategoryMap.Add(etContactList, 'Contact');
  FEventCategoryMap.Add(etContactListComplete, 'Contact');
  FEventCategoryMap.Add(etContactStatus, 'Contact');
  FEventCategoryMap.Add(etContactStatusDetail, 'Contact');
  FEventCategoryMap.Add(etDialBegin, 'Dial');
  FEventCategoryMap.Add(etDialEnd, 'Dial');
  FEventCategoryMap.Add(etDialState, 'Dial');
  FEventCategoryMap.Add(etDTMFBegin, 'DTMF');
  FEventCategoryMap.Add(etDTMFEnd, 'DTMF');
  FEventCategoryMap.Add(etEndpointDetail, 'Endpoint');
  FEventCategoryMap.Add(etEndpointDetailComplete, 'Endpoint');
  FEventCategoryMap.Add(etEndpointList, 'Endpoint');
  FEventCategoryMap.Add(etEndpointListComplete, 'Endpoint');
  FEventCategoryMap.Add(etIdentifyDetail, 'Endpoint');
  FEventCategoryMap.Add(etTransportDetail, 'Endpoint');
  FEventCategoryMap.Add(etFAXSession, 'FAX');
  FEventCategoryMap.Add(etFAXSessionsComplete, 'FAX');
  FEventCategoryMap.Add(etFAXSessionsEntry, 'FAX');
  FEventCategoryMap.Add(etFAXStats, 'FAX');
  FEventCategoryMap.Add(etFAXStatus, 'FAX');
  FEventCategoryMap.Add(etReceiveFAX, 'FAX');
  FEventCategoryMap.Add(etSendFAX, 'FAX');
  FEventCategoryMap.Add(etDeadlockStart, 'System');
  FEventCategoryMap.Add(etFlash, 'Unknown');
  FEventCategoryMap.Add(etFullyBooted, 'System');
  FEventCategoryMap.Add(etLoad, 'System');
  FEventCategoryMap.Add(etLoadAverageLimit, 'System');
  FEventCategoryMap.Add(etMemoryLimit, 'System');
  FEventCategoryMap.Add(etReload, 'System');
  FEventCategoryMap.Add(etSessionLimit, 'System');
  FEventCategoryMap.Add(etSessionTimeout, 'System');
  FEventCategoryMap.Add(etShutdown, 'System');
  FEventCategoryMap.Add(etUnload, 'System');
  FEventCategoryMap.Add(etWink, 'Unknown');
  FEventCategoryMap.Add(etMeetmeEnd, 'Conference');
  FEventCategoryMap.Add(etMeetmeJoin, 'Conference');
  FEventCategoryMap.Add(etMeetmeLeave, 'Conference');
  FEventCategoryMap.Add(etMeetmeList, 'Conference');
  FEventCategoryMap.Add(etMeetmeListRooms, 'Conference');
  FEventCategoryMap.Add(etMeetmeMute, 'Conference');
  FEventCategoryMap.Add(etMeetmeTalkRequest, 'Conference');
  FEventCategoryMap.Add(etMeetmeTalking, 'Conference');
  FEventCategoryMap.Add(etMessageWaiting, 'MWI');
  FEventCategoryMap.Add(etMiniVoiceMail, 'MWI');
  FEventCategoryMap.Add(etMWIGet, 'MWI');
  FEventCategoryMap.Add(etMWIGetComplete, 'MWI');
  FEventCategoryMap.Add(etMixMonitorMute, 'Monitoring');
  FEventCategoryMap.Add(etMixMonitorStart, 'Monitoring');
  FEventCategoryMap.Add(etMixMonitorStop, 'Monitoring');
  FEventCategoryMap.Add(etParkedCall, 'Parking');
  FEventCategoryMap.Add(etParkedCallGiveUp, 'Parking');
  FEventCategoryMap.Add(etParkedCallSwap, 'Parking');
  FEventCategoryMap.Add(etParkedCallTimeOut, 'Parking');
  FEventCategoryMap.Add(etUnParkedCall, 'Parking');
  FEventCategoryMap.Add(etPeerStatus, 'DeviceStatus');
  FEventCategoryMap.Add(etRegistry, 'DeviceStatus');
  FEventCategoryMap.Add(etSIPQualifyPeerDone, 'DeviceStatus');
  FEventCategoryMap.Add(etPresenceStateChange, 'DeviceStatus');
  FEventCategoryMap.Add(etPresenceStateListComplete, 'DeviceStatus');
  FEventCategoryMap.Add(etPresenceStatus, 'DeviceStatus');
  FEventCategoryMap.Add(etQueueCallerAbandon, 'Queue');
  FEventCategoryMap.Add(etQueueCallerJoin, 'Queue');
  FEventCategoryMap.Add(etQueueCallerLeave, 'Queue');
  FEventCategoryMap.Add(etQueueEntry, 'Queue');
  FEventCategoryMap.Add(etQueueMember, 'Queue');
  FEventCategoryMap.Add(etQueueMemberAdded, 'Queue');
  FEventCategoryMap.Add(etQueueMemberPause, 'Queue');
  FEventCategoryMap.Add(etQueueMemberPenalty, 'Queue');
  FEventCategoryMap.Add(etQueueMemberRemoved, 'Queue');
  FEventCategoryMap.Add(etQueueMemberRinginuse, 'Queue');
  FEventCategoryMap.Add(etQueueMemberStatus, 'Queue');
  FEventCategoryMap.Add(etQueueParams, 'Queue');
  FEventCategoryMap.Add(etQueueStatusComplete, 'Queue');
  FEventCategoryMap.Add(etQueueSummaryComplete, 'Queue');
  FEventCategoryMap.Add(etRTCPReceived, 'RTP');
  FEventCategoryMap.Add(etRTCPSent, 'RTP');
  FEventCategoryMap.Add(etChanSpyStart, 'Monitoring');
  FEventCategoryMap.Add(etChanSpyStop, 'Monitoring');
  FEventCategoryMap.Add(etAttendedTransfer, 'Transfer');
  FEventCategoryMap.Add(etBlindTransfer, 'Transfer');
  FEventCategoryMap.Add(etUserEvent, 'UserEvent');
  FEventCategoryMap.Add(etVarSet, 'Variables');
  FEventCategoryMap.Add(etMCID, 'Unknown');
  FEventCategoryMap.Add(etDBGetResponse, 'System');
  FEventCategoryMap.Add(etDBGetComplete, 'System');
  FEventCategoryMap.Add(etChannelHungup, 'CallControl');
  FEventCategoryMap.Add(etChannelsHungupListComplete, 'System');
end;

initialization
  InitializeMaps;

finalization
  FreeAndNil(FEventTypeMap);
  FreeAndNil(FEventPriorityMap);
  FreeAndNil(FEventCategoryMap);

end.
